### ISSUE TITLE
Cannot write to a file with Win64 (and probably Win32) executable

### ISSUE THREAD

**Issue by camdenb** [MisterDA/love-release#17]
When attempting to `love.filesystem.write` (which works well when I run the .love file) from a packaged .exe, no file is ever saved.

**Comment by Positive07** [comment]
Remember that when you fuse the game the data is saved to `AppData/YourIdentity` instead of `AppData/LOVE/YourIdentity`

**Comment by MisterDA** [comment]
Yes, I don't see how your problem could be related in any way with love-release... Double-check your code and the folders @Positive07 mentioned !

**Comment by camdenb** [comment]
Ah, my bad. Thank you!
