### ISSUE TITLE
Innosetup.iss not found

### ISSUE THREAD

**Issue by sarahgould** [MisterDA/love-release#18]
I'm having a few issues with getting the Windows Installer to work. First off, the default install directories are under "Program Files," while the script looks under "Program Files (x86)" (an easy fix). But more seriously, I get the following error that prevents the installer form working at all:

```Error on line 21 in C:\innosetup.iss: File not found.```

**Comment by MisterDA** [comment]
I'm sorry I'm taking so long to fix this, but I'm considering a partial rewrite of the script. I hope I'll fix this on the way.
