### ISSUE TITLE
LOVE_GT_090 incorrectly set to false, Windows 7

### ISSUE THREAD

**Issue by wilbefast** [MisterDA/love-release#19]
I've had some issues running the script on my new Windows 7 setup. It seems that the variable ``LOVE_GT_090`` is incorrectly set ``false`` for my 0.9.2 game, meaning that the script tries to curl ``love-0.9.2-win-x86`` which doesn't exist in [https://bitbucket.org/rude/love/downloads/](https://bitbucket.org/rude/love/downloads/). 

Note: the version wasn't detected at all at first: it was using the default 0.9.1 despite the 0.9.2 in the conf.lua file. I hard set the default ``LOVE_VERSION=0.9.2`` and ``LOVE_GT_090=true`` in the script in order to fix this.

This may have something to do with some grep and gawk errors I'm getting:
```
$ ./do-build.sh > log.txt
grep: invalid option -- o
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
grep: invalid option -- o
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
gawk: cmd. line:1: END { exit ( !(  >= 0.8)); }
gawk: cmd. line:1:                  ^ parse error
gawk: cmd. line:1: END { exit ( !(  >= 0.8)); }
gawk: cmd. line:1:                         ^ parse error
gawk: cmd. line:1: END { exit ( !(  >= 0.8)); }
gawk: cmd. line:1:                          ^ parse error
gawk: cmd. line:1: END { exit ( !(  >= 0.9)); }
gawk: cmd. line:1:                  ^ parse error
gawk: cmd. line:1: END { exit ( !(  >= 0.9)); }
gawk: cmd. line:1:                         ^ parse error
gawk: cmd. line:1: END { exit ( !(  >= 0.9)); }
gawk: cmd. line:1:                          ^ parse error
```

**Comment by MisterDA** [comment]
Hi ! Thank you for the error report. For now I don't really know how to fix it, but I've been rewriting love-release for a week and I'll be done in a couple of days, so it will certainely fix your problem.
You can check the progress on the [rewrite](https://github.com/MisterDA/love-release/tree/rewrite) branch. To get a look at the new `compare_version` function (which is used to... compare two LÖVE version strings), you can check this [Gist](https://gist.github.com/MisterDA/e41753bd2ab4c25bb0f1) (I hope I haven't done any basic/logic mistakes on such a simple thing).

Oh, and it never should have been named `LOVE_GT_090` but `LOVE_GE_090` as the variable is set to true if LÖVE is greater-or-equal (and not greater-than) 0.9.0. I'm sorry that love-release is so broken ! But hopefully the rewrite will fix the problems you've encountered.

**Comment by wilbefast** [comment]
Righto, I'll give that a look tomorrow night!
