### ISSUE TITLE
sed -r isn't working on Mac OS X

### ISSUE THREAD

**Issue by Floriaen** [MisterDA/love-release#20]
OSX sed is older version.
In order to have love-release working I installed gnu sed:

	brew install --default-names gnu-sed

Thank you for the great work.

**Comment by MisterDA** [comment]
:cry: portability...
The script requires GNU versions of sed, getopt and perhaps zip too.
I beleive `sed -E` could be used instead [man sed](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sed.1.html) on OSX, but that won't work with GNU.
I'll add a note in the readme if no workaround is possible.

**Comment by Floriaen** [comment]
I did it and the script was no-op :/

**Comment by MisterDA** [comment]
Where did it fail ? Do you use the master branch, or the [rewrite](https://github.com/MisterDA/love-release/tree/rewrite) (that will be finished in a few hours I hope) ?

**Comment by Floriaen** [comment]
I didn't investigate more, the script did nothing with the modification.
I am using the code from the master branch.
Let me try with the rewrite one and I let you know.

**Comment by Floriaen** [comment]
Well... make install gave me this:

install -m 0755 'build/love-release' '/usr/bin'
install -m 0755 -d '/usr/share/love-release' '/usr/share/love-release/scripts' '/usr/share/bash-completion/completions'
install -m 0755 scripts/* '/usr/share/love-release/scripts'
install -m 0644 -t '/usr/share/love-release' README.md conf.lua modules.md
install: illegal option -- t
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
