### ISSUE TITLE
Read only variable

### ISSUE THREAD

**Issue by Germanunkol** [MisterDA/love-release#26]
Since commit 86a936fbf026c1f2c417fe4fe5fed64a7d45afd6, I can no longer build "binaries":

    Generating trAInsported with LÖVE 0.9.1 for Debian...
    /usr/share/love-release/scripts/debian.sh: line 3: OPTIONS: readonly variable
    Generating trAInsported with LÖVE 0.9.1 for Mac OS X...
    /usr/share/love-release/scripts/macosx.sh: line 3: OPTIONS: readonly variable
    Generating trAInsported with LÖVE 0.9.1 for Windows...
    /usr/share/love-release/scripts/windows.sh: line 3: OPTIONS: readonly variable

Works fine when checkout out the commit before that one.
I'm on Ubuntu 15.04.

the .love version gets generated just fine.

**Comment by MisterDA** [comment]
Well it's because I'm stupid. I'll fix this in a moment, sorry :)
