### ISSUE TITLE
Can't build on android if there is a space in the title

### ISSUE THREAD

**Issue by raffomania** [MisterDA/love-release#29]
When building on android, spaces and other special characters in the game title get substituted with a hyphen to create the package name.
But hyphens don't seem to be allowed for a package name in android, I get the following error when building:

    .cache/love-release/android/love-android-sdl2/bin/AndroidManifest.xml:2: 
        Tag <manifest> attribute package has invalid character '-'.

**Comment by MisterDA** [comment]
Thanks for the note ! love-release doesn't (yet) support the android port in the Lua implementation, but I'll remember this for later.
