### ISSUE TITLE
Building for android discards changes in the project directory

### ISSUE THREAD

**Issue by raffomania** [MisterDA/love-release#30]
Line 151 in `scripts/android.sh` does `git checkout --` in the project directory. This caused some confusion for me ;) Is there a reason for this behavior?

**Comment by MisterDA** [comment]
When the android script creates a package, it adds a some files in your project (but I don't remember what and where). At the time, I thought that `git checkout --` was a good idea to reset the project directory to a previous state, but now that you say it...
It's terrible, I'm sorry if I have deleted your code ! I'm going to remove this line asap, then I'll take a look to know how I can cleanly delete the android generated files.
