### ISSUE TITLE
getopt option unrecognized

### ISSUE THREAD

**Issue by thelukester92** [MisterDA/love-release#32]
When I add --Micon to the arguments when running on a Mac, I get an option unrecognized error. Adding "Micon:" to the long options in the main .sh file fixes this problem (and other extended options as well).

Is there a known reason for this? Am I doing something wrong, or is my fix correct?

**Comment by MisterDA** [comment]
BSD/Mac/POSIX getopt doesn't recognize long options. You have to use GNU getopt for this.
