### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by nunodonato** [MisterDA/love-release#38]
Hi, sorry this is more of a support request :/

I can't get past the install part of this using lua rocks,
typing luarocks install love-release just outputs

Error: No results matching query were found.

any tips? :/ or how can I build from the git code?

**Comment by MisterDA** [comment]
My guess is that you're using a luarocks with Lua > 5.1. I've made Lua 5.1 a requirement for love-release because LÖVE uses LuaJIT in Lua 5.1 mode (and perhaps Lua 5.2 additions). As love-release currently loads the `conf.lua` file, I thought that is was best to use only Lua 5.1.

There's [this line](https://github.com/MisterDA/love-release/blob/master/rockspecs/love-release-2.0.2-0.rockspec#L19) in the rockspec `lua ~> 5.1` and a luarocks install that uses a newer version of Lua won't find love-release.

As stated in #27, love-release should not try to load `conf.lua` so there will be no need to stay at Lua 5.1 (if there was any).

For now you can use a Lua 5.1 luarocks, or clone the repo, remove the line in the rockspec and install love-release with `luarocks make rockspecs/love-release-scm-1.rockspec`.

**Comment by MisterDA** [comment]
There is another reason to stay at Lua 5.1 : love-release uses [brimworks/lua-zip](https://github.com/brimworks/lua-zip) as a binding for [libzip](http://www.nih.at/libzip/) to handle zip archives. For now lua-zip is dependent on Lua 5.1 but it's really a simple thing to make it compatible with newer versions of Lua. I'll fork and improve the binding later.

**Comment by technomancy** [comment]
I am using luarocks with 5.1 (I removed 5.2 from my system) and I still get this when installing:

```
$ luarocks install --local love-release
Installing https://rocks.moonscript.org/love-release-2.0.3-1.rockspec...
Using https://rocks.moonscript.org/love-release-2.0.3-1.rockspec... switching to 'build' mode

Missing dependencies for love-release:
lua-zip 


Error: Could not satisfy dependency: lua-zip 
```

**Comment by MisterDA** [comment]
lua-zip has no officially released version and is still listed as "in development" on LuaRocks, so you have to install it with:
```sh
luarocks install --server=http://luarocks.org/dev lua-zip
```
In your case, add the `--local` switch.

I'm working on a little fork to fix some issues with lua-zip, then the author will have set a 'stable' version and upload it to LuaRocks to enable the dependency process.

**Comment by technomancy** [comment]
This fails too:

```
$ luarocks install --local --server=http://luarocks.org/dev lua-zip
Installing http://luarocks.org/dev/lua-zip-git-1.rockspec...
Using http://luarocks.org/dev/lua-zip-git-1.rockspec... switching to 'build' mode

Error: Could not find expected file libzip.a, or libzip.so, or libzip.so.* for ZIP -- you may have to install ZIP in your system and/or pass ZIP_DIR or ZIP_LIBDIR to the luarocks command. Example: luarocks install lua-zip ZIP_DIR=/usr/local
```

I guess I will stick with the old bash-based version of love-release for now.

**Comment by MisterDA** [comment]
Have you installed libzip <http://www.nih.at/libzip/> ?

If you have Ubuntu/Debian:
# apt-get install libzip4 libzip-dev

If you have macOS, you can use Homebrew <http://brew.sh/>:
$ brew install libzip

2016-09-03 12:06 GMT+02:00 Phil Hagelberg <notifications@github.com>:

**Comment by MisterDA** [comment]
> 2016-09-03 12:06 GMT+02:00 Phil Hagelberg @technomancy :

> This fails too:
>
> ```
> $ luarocks install --local --server=http://luarocks.org/dev lua-zip
> Installing http://luarocks.org/dev/lua-zip-git-1.rockspec...
> Using http://luarocks.org/dev/lua-zip-git-1.rockspec... switching to 'build' mode
>
> Error: Could not find expected file libzip.a, or libzip.so, or libzip.so.* for ZIP
> -- you may have to install ZIP in your system and/or pass ZIP_DIR or ZIP_LIBDIR
> to the luarocks command. Example: luarocks install lua-zip ZIP_DIR=/usr/local
> ```
>
> I guess I will stick with the old bash-based version of love-release for
> now.

Have you installed [libzip](http://www.nih.at/libzip/) ?

If you have Ubuntu/Debian:

    # apt-get install libzip4 libzip-dev

If you have macOS, you can use [Homebrew](http://brew.sh/):

    $ brew install libzip

**Comment by rm-code** [comment]
@MisterDA I think the installation instructions for libzip should also be added to the README.

**Comment by rm-code** [comment]
Hm ... there seems to be an issue with lua-zip on Mac OS 

```
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c lua_zip.c -o lua_zip.o -I/usr/local/include
In file included from lua_zip.c:3:
/usr/local/include/zip.h:59:10: fatal error: 'zipconf.h' file not found
#include <zipconf.h>
         ^
1 error generated.

Error: Build error: Failed compiling object lua_zip.o
```

**Comment by Positive07** [comment]
There is a file in the `lib` folder of `libzip` called `make_zipconf` maybe that is a place to start looking... But otherwise I have no idea sorry (Windows user)

**Comment by MisterDA** [comment]
Yes... I remember that `zipconf.h` is not installed where you would expect it. I think I added a symlink from it to `/usr/include/zipconf.h` but it's an ugly thing to do.
There are some comments here [legacy-homebrew#13390](https://github.com/Homebrew/legacy-homebrew/issues/13390).

Have you tried to build lua-zip with CMake?

If not, could you try using pkg-config?
```
gcc -O2 -fPIC $(pkg-config --cflags --libs lua51 libzip) -c lua_zip.c
```

If pkg-config works and CMake does not, then it's probably a bug with CMake. If that's the case, we should rewrite the Makefile of lua-zip.

**Comment by rm-code** [comment]
> Have you tried to build lua-zip with CMake?

Not yet, will try when I get home. 

> If pkg-config works and CMake does not, then it's probably a bug with CMake. If that's the case, we should rewrite the Makefile of lua-zip.

The repository of lua-zip looks pretty dead though :/

**Comment by Positive07** [comment]
lua-zip is dead, MisterDA is the only person working on it. Unfortunately there is no decent zip library for Lua (for some odd reason)
