### ISSUE TITLE
Include lib directory?

### ISSUE THREAD

**Issue by egordorichev** [MisterDA/love-release#44]
My game has `lib` directory, and it seems, like it is not included into generated love file. 
How to fix that?

**Comment by egordorichev** [comment]
It doesn't include any project directories. Unpacked love file consists only from top-path files.

**Comment by Positive07** [comment]
First, you can edit your posts, no need to double post (double posting means that persons subscribed to the thread receive two emails while if you edit we receive one and we will come and read the whole thing over here)

Second, could you show what you mean with a project structure written like this:
```
> lib
-->mylib.lua
> src
-->file.lua
>main.lua
>config.lua
```
Or similar, this lets us see what the structure actually looks like, alternatively post an image of how your folders are structured....

From your posts it's not that easy to understand what you mean

**Comment by egordorichev** [comment]
You can find the whole project [here](https://github.com/egordorichev/cga17). 

It structured kind-of like you've showed:

```
> data
--> images
--> music
--> sounds
--> fonts
> lib
--> libs here
> linit
--> engine here
> main.lua
> config.lua
> other game scripts

**Comment by Positive07** [comment]
So when you package the LÖVE file only has `main.lua`, `config.lua` and `other game scripts`?

Or does it have `config.lua` and the `data` folder?

**Comment by egordorichev** [comment]
It has only main.lua, config.lua and other game scripts. 

![](http://i.imgur.com/yUGqJlB.png)

**Comment by Positive07** [comment]
Can you try patching [`project.lua`](https://github.com/MisterDA/love-release/blob/master/src/project.lua#L63L79) with the fix I proposed at [#36](https://github.com/MisterDA/love-release/issues/36#issuecomment-302622060) and see if that works?

**Comment by egordorichev** [comment]
Hm, sorry, where the `project.lua` can be found in linux system?

**Comment by Positive07** [comment]
Try `luarocks --path` in the command line and that should give you a location where you can find a `love-release` folder or something

**Comment by egordorichev** [comment]
Ok, thanks a lot! The patch fixed this issue.
