### ISSUE TITLE
How to release an apk for android?

### ISSUE THREAD

**Issue by possatti** [MisterDA/love-release#47]
This might be a really dumb question. But I could not find any instructions on how to do it. The help command (`love-release -h`) doesn't say anything about it either.

How do I release an apk version of my game?

Thanks.

**Comment by Positive07** [comment]
This was implemented back when love-release was coded in Bash. But was not re-implemented after the rewrite in Lua.

It's in the TODO list and will be implemented (hopefully soon)

**Comment by possatti** [comment]
Thanks for letting me know. Is this TODO list written somewhere that I can watch? It could be a good idea to use milestones or write it on the wiki.

**Comment by Positive07** [comment]
Refere to issue #40 for a Roadmap for love-release

**Comment by possatti** [comment]
Nice. Thanks.

**Comment by Positive07** [comment]
I'll write down some details on how this will most likely be implemented, so it can serve as reference to anyone that wants to implement it.

First this should be written as an script in `src/scripts` called `android.lua`.
This script should:
- Check the availability of tools (Android SDK, NDK, JDK, Gradle, ...)
- Generate `AndroidManifest.xml` using a template and the information gathered from the CLI and `conf.lua`
- Call `gradle` with the build information
