### ISSUE TITLE
attempt to call global 'require' (a nil value)

### ISSUE THREAD

**Issue by egordorichev** [MisterDA/love-release#51]
```
> love-release
/usr/bin/lua5.1: /usr/local/share/lua/5.1/love-release/pipes/conf.lua:23: conf.lua:3: attempt to call global 'require' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/love-release/pipes/conf.lua:23: in function </usr/local/share/lua/5.1/love-release/pipes/conf.lua:14>
	(tail call): ?
	...luarocks/rocks/love-release/2.0.4-1/bin/love-release:11: in main chunk
	[C]: ?
```

**Comment by Positive07** [comment]
This project uses [loadconf](https://github.com/Alloyed/loadconf) to execute the `conf.lua` file in a safe environment, `require` is not included in this sandbox.

This is related to issue #27 and #49.

If you want to provide a `conf.lua` that works both in LÖVE and love-release, make sure you first check if you are running on LÖVE with something similar to:

```lua
if love.filesystem then
  --This is LÖVE
end
```

**Comment by egordorichev** [comment]
I don't have a config for love-release. Here is my conf.lua: https://github.com/egordorichev/neko8/blob/master/conf.lua

It was running ok, but something happened and it broke. Debian package building was broken all time.

**Comment by Positive07** [comment]
love-release tries to load `conf.lua` even if you don't have specific configurations for love-release

Try to do something like
```
if not require then
  love.conf = function () end
else
  --Your code goes here
end
```

**Comment by egordorichev** [comment]
Oh, that works. Thank you :)
