### ISSUE TITLE
.deb release with LOVE included

### ISSUE THREAD

**Issue by yancouto** [MisterDA/love-release#52]
Hi! First of all, thanks for love-release, it has helped me a lot.

I have also used love-release to create `.deb` files for Ubuntu/Debian distribution. The problem is: the `.deb` file does not contains LOVE itself, and rather depends on it. That is a problem for two main reasons:
- LOVE updates often and is not backward-compatible with older versions. If LOVE is not packaged with the game then in the (not so far future) the game will stop working unless it is updated for the new LOVE version.
- As LOVE updates often, the version on the repositories is not always the latest. As of now, for example, the current LOVE version is 0.10.2 but the only version I can find in my Debian is 0.9.1 (and 0.10 has been released for more than 1 year!)

Is it possible to do this now? If not, is it plausible to add this to love-release?

I have been searching for some time but have found no better solution than including the correct love `.deb`s and making a install script. When distributing a game, I think it is better to make it as easy for the player as possible, and my solution is not ideal.

Thank you!

**Comment by MisterDA** [comment]
Hi,

The main purpose of packages with GNU/Linux distributions, such as Debian and its `.deb` packages is to create such dependencies! which of course is a problem when they become obsolete. The [love](https://packages.debian.org/sid/love) package itself depends on a lot of libraries.

I am not aware of any way of embedding a debian package into another (if you wanted to embed love pkg into yours). You could do it by hand, but the resulting package won't follow [Debian's packaging policy](https://wiki.debian.org/Games/Love2d).

LÖVE is still in development, so API changes are an issue for game compatibility but we have to deal with it, which means that we basically have to port games every new version. Attemps of compatibility layers have been made.

On Debian you won't have a chance to get an updated version of LÖVE. I would reach out to the devs and ask for the package to be updated, but I'm not sure if it works like this.

- with Ubuntu you can ask your players to use [bartbes' PPA](https://launchpad.net/~bartbes/+archive/ubuntu/love-stable) which functions as an additionnal package source, and has the latest version of LÖVE. It's efficient, and quite practical.
- universal Linux packages such as [Snappy](https://www.ubuntu.com/desktop/snappy), [Flatpak](https://flatpak.org/), or [AppImage](https://appimage.org/). I haven't tried any of the three and love-release does not support them (yet?), but it seems to be the way to go if you can't use native packages from the distribution.

Good luck!
