### ISSUE TITLE
Add support for Love 11.1

### ISSUE THREAD

**Issue by oniietzschan** [MisterDA/love-release#53]
Hiya, Love 11.1 is out! I was actually going to send you a PR for this, but as I was getting into it, I noticed something that miiiight be a problem!

I noticed in the scripts that love-release tries to grab a filename like: `"love-"..tostring(project.loveVersion).."-win"`, where `project.loveVersion` is a semver like `1.2.3`, of course. However, since the new versioning convention started, it looks like the binaries are no longer being named with this convention: https://bitbucket.org/rude/love/downloads/, ie. the files are now named `love-11.1-*`, rather than `love-11.1.0-*`.

I could very well be wrong, but I suspect that simply trying to add `11.1` as a supported version to love-release may not work?

**Comment by MisterDA** [comment]
Thanks for the report.
Could you check that your problem is fixed ? then I'll tag a new version.
I have quickly tested Windows and macOS.

**Comment by oniietzschan** [comment]
Hey, sorry for the late test, I don't typically work on Lua stuff during the weekend so I sort of forgot about this until now.

It looks like something else changed on master, too? Do I need to grab a different luazip dependency?

```
$ love-release -W
sh: love: command not found
/usr/bin/lua5.1: /usr/share/lua/5.1/love-release/script.lua:7: module 'misterda.zip' not found:No LuaRocks module found for misterda.zip
	no field package.preload['misterda.zip']
	no file '/root/.luarocks/share/lua/5.1/misterda/zip.lua'
	no file '/root/.luarocks/share/lua/5.1/misterda/zip/init.lua'
	no file '/usr/share/lua/5.1/misterda/zip.lua'
	no file '/usr/share/lua/5.1/misterda/zip/init.lua'
	no file './misterda/zip.lua'
	no file '/usr/lib/lua/5.1/misterda/zip.lua'
	no file '/usr/lib/lua/5.1/misterda/zip/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/misterda/zip.so'
	no file '/usr/lib/lua/5.1/misterda/zip.so'
	no file './misterda/zip.so'
	no file '/usr/lib/lua/5.1/loadall.so'
	no file '/root/.luarocks/lib/lua/5.1/misterda.so'
	no file '/usr/lib/lua/5.1/misterda.so'
	no file './misterda.so'
	no file '/usr/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/share/lua/5.1/love-release/script.lua:7: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.1/love-release/scripts/love.lua:5: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.1/love-release/pipes/args.lua:103: in function 'args'
	...arocks/rocks-5.1/love-release/scm-1/bin/love-release:11: in main chunk
	[C]: ?
```

**Comment by oniietzschan** [comment]
Okay, I see your fork. It took me a little while to figure out that it was under "lua-libzip". That's definitely a pretty crappy design decision for luarocks, I think; that library names are reserved for the first person that grabs them, as opposed to allowing different vendor namespaces for the same library. Trying it out now.

**Comment by oniietzschan** [comment]
Alright! I tried it out again with `lua-libzip` installed instead and everything worked! Don't forget to update README.md with the correct library.

**Comment by hishamhm** [comment]
@oniietzschan namespaces are supported in the current `master` for LuaRocks. Development has picked up speed again! :)

**Comment by MisterDA** [comment]
Noted.
v2.0.6 is out and supports LÖVE 11.1.
I will use namespaces when LuaRocks gets to version 3! Thanks for everything.
