### ISSUE TITLE
Error when installing: "source and destination are the same file"

### ISSUE THREAD

**Issue by MisterDA** [MisterDA/love-release#68]
Just to be clear, installing through luarocks should get me that?

```
$ luarocks install love-release --local           
Installing https://luarocks.org/love-release-2.0.12-2.rockspec

Cloning into 'love-release'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 26 (delta 2), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (26/26), 16.67 KiB | 16.67 MiB/s, done.
Resolving deltas: 100% (2/2), done.

Error: Build error: Failed installing src/scripts/macosx.lua in /home/murks/.luarocks/lib/luarocks/rocks-5.3/love-release/2.0.12-2/lua/love-release/scripts/macosx.lua: The source and destination are the same files
```

_Originally posted by @hollunder in https://github.com/MisterDA/love-release/issues/67#issuecomment-511912012_

No. This bug was not present in 2.0.11. It should be fixed in 2.0.12-3 but is not. I won’t upload this, but rather work on 2.0.13. The bug is still present in 2.0.13. I don’t know what causes it.

I also asked about it in https://github.com/luarocks/luarocks/issues/1062.

**Comment by fexra** [comment]
Got it to work with the ``--dev`` flag.

**Comment by hollunder** [comment]
I tried it yesterday and it builds something, although running that on a Mac failed.
It tried to access some accessibility feature on the Mac I think? Very weird.
I don't have a Mac at home so unfortunately I'm rather useless for debugging.

**Comment by MisterDA** [comment]
Fixed in LuaRocks upstream, soon to be released.
