### ISSUE TITLE
Install - Luarocks - Remote/upstream conflict

### ISSUE THREAD

**Issue by BearHeathen** [MisterDA/love-release#71]
System: Windows 10 x64, Lua 5.3, Luarocks > 3.0, everything Lua-related added to PATH, all dependencies met as per instructions (zlib, libzip, etc)...

Receiving the following error: 

```
PS C:\Users\<MY USERNAME>\Documents\Lua\love-release> luarocks install love-release
Installing https://luarocks.org/love-release-2.0.15-1.rockspec
Cloning into 'love-release'...
warning: Could not find remote branch v2.0.15 to clone.
fatal: Remote branch v2.0.15 not found in upstream origin

Error: Failed cloning git repository.
```

Pay no attention to the CWD, I was just messing about with git. This happens no matter where I attempt to perform the install.

Possibly a HEAD tag issue?

**Comment by MisterDA** [comment]
It looks like LuaRocks is trying to fetch a branch from the git repo, but
v2.0.15 is a tag and not a branch. I may have gotten the URL syntax wrong
in the rockspec file. I'll fix that.
In the meantime, you can install the development package.

**Comment by BearHeathen** [comment]
The dev package works flawlessly. Many thanks!

**Comment by MisterDA** [comment]
The problem was that I had not pushed the v2.0.15 tag. This had already happen to me. It’s fixed now. Thanks for reporting!
